-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  RIDE & GO — NEXUS MIGRATION 0002
--  Generated by Phase 1B implementation. Covers every persistent entity
--  defined in packages/database/src/schema.ts for the ride & go subsystem:
--  drivers, vehicles, ride lifecycle, pools, fare/promo/payment, SOS,
--  incidents, luggage, skins, vehicle scans, maintenance, fleet
--  deployment, heatmap predictions, places, ratings, curators, rewards,
--  audit log.
--
--  Idempotent guards (`IF NOT EXISTS`, `DO $$ ... EXCEPTION`) keep the
--  migration re-runnable in CI / shadow DB pipelines.
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ENUMS ─────────────────────────────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE "ride_status" AS ENUM (
    'requested','matching','offered','accepted','driver_enroute','arrived',
    'in_progress','completed','cancelled_by_rider','cancelled_by_driver',
    'cancelled_by_system','no_drivers','expired','disputed'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "ride_type" AS ENUM (
    'solo','pool','women_only','luggage','premium','accessibility'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "vehicle_type" AS ENUM (
    'bicycle','electric_scooter','motorcycle','auto','mini','sedan','suv','premium','van'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "driver_status" AS ENUM (
    'offline','online','on_break','enroute_to_pickup','arrived_at_pickup',
    'on_trip','suspended','banned'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "vehicle_status" AS ENUM (
    'active','maintenance','retired','impounded','inspection_due'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "pool_status" AS ENUM (
    'open','filling','matched','dispatched','completed','cancelled','expired'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "sos_status" AS ENUM (
    'triggered','acknowledged','resolved','false_alarm','escalated'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "incident_status" AS ENUM (
    'reported','investigating','awaiting_evidence','resolved','rejected','escalated_to_legal'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "incident_severity" AS ENUM ('low','medium','high','critical');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "ride_payment_status" AS ENUM (
    'pending','authorized','captured','refunded','partial_refund','failed','cod_pending','cod_collected'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "ride_payment_method" AS ENUM (
    'wallet','upi','card','netbanking','cod','campus_pass'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "cod_verification_status" AS ENUM (
    'pending','otp_sent','verified','failed','expired'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "curator_shift_status" AS ENUM (
    'scheduled','checked_in','on_break','completed','missed','cancelled'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "curator_tier" AS ENUM ('bronze','silver','gold','platinum','elite');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "maintenance_type" AS ENUM (
    'routine','repair','inspection','battery_swap','tire_change','oil_change','detailing','recall'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "skin_rarity" AS ENUM ('common','rare','epic','legendary','mythic');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "deployment_status" AS ENUM (
    'planned','active','paused','completed','rolled_back'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE TYPE "trip_phase" AS ENUM (
    'idle','matching','pickup','transit','dropoff','wrap_up'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- TABLES ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "ride_drivers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "license_number" varchar(64) NOT NULL,
  "license_expiry" timestamp with time zone,
  "license_image_url" text,
  "aadhaar_last4" varchar(4),
  "pan_number" varchar(16),
  "police_verification_id" varchar(100),
  "police_verified_at" timestamp with time zone,
  "is_verified" boolean DEFAULT false NOT NULL,
  "is_women_only" boolean DEFAULT false NOT NULL,
  "is_premium_eligible" boolean DEFAULT false NOT NULL,
  "is_accessibility_trained" boolean DEFAULT false NOT NULL,
  "trust_score" numeric(5,2) DEFAULT '5.00' NOT NULL,
  "acceptance_rate" numeric(5,2) DEFAULT '1.00' NOT NULL,
  "cancellation_rate" numeric(5,2) DEFAULT '0.00' NOT NULL,
  "completed_trips" integer DEFAULT 0 NOT NULL,
  "total_earnings" numeric(14,2) DEFAULT '0' NOT NULL,
  "rating" numeric(3,2) DEFAULT '5.00' NOT NULL,
  "rating_count" integer DEFAULT 0 NOT NULL,
  "current_vehicle_id" uuid,
  "preferred_zone_id" uuid,
  "status" "driver_status" DEFAULT 'offline' NOT NULL,
  "current_lat" numeric(10,7),
  "current_lng" numeric(10,7),
  "last_ping_at" timestamp with time zone,
  "fcm_token" text,
  "apns_token" text,
  "metadata" jsonb DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_vehicles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "driver_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "vehicle_type" "vehicle_type" NOT NULL,
  "make" varchar(64),
  "model" varchar(64),
  "year" integer,
  "color" varchar(32),
  "license_plate" varchar(24) NOT NULL,
  "rc_image_url" text,
  "fitness_image_url" text,
  "insurance_image_url" text,
  "insurance_expiry" timestamp with time zone,
  "permit_number" varchar(64),
  "seating_capacity" smallint DEFAULT 4 NOT NULL,
  "luggage_capacity" smallint DEFAULT 2 NOT NULL,
  "is_electric" boolean DEFAULT false NOT NULL,
  "battery_kwh" numeric(5,2),
  "range_km" integer,
  "skin_id" uuid,
  "odometer_km" integer DEFAULT 0 NOT NULL,
  "status" "vehicle_status" DEFAULT 'active' NOT NULL,
  "last_inspection_at" timestamp with time zone,
  "next_inspection_due" timestamp with time zone,
  "metadata" jsonb DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_driver_shifts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "driver_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "started_at" timestamp with time zone NOT NULL,
  "ended_at" timestamp with time zone,
  "planned_end_at" timestamp with time zone,
  "breaks" jsonb DEFAULT '[]' NOT NULL,
  "trips" integer DEFAULT 0 NOT NULL,
  "earnings" numeric(14,2) DEFAULT '0' NOT NULL,
  "online_seconds" integer DEFAULT 0 NOT NULL,
  "metadata" jsonb DEFAULT '{}' NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_requests" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "rider_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "driver_id" uuid,
  "vehicle_id" uuid,
  "pool_id" uuid,
  "ride_type" "ride_type" DEFAULT 'solo' NOT NULL,
  "status" "ride_status" DEFAULT 'requested' NOT NULL,
  "pickup_lat" numeric(10,7) NOT NULL,
  "pickup_lng" numeric(10,7) NOT NULL,
  "pickup_label" text NOT NULL,
  "pickup_building" varchar(128),
  "pickup_floor" varchar(32),
  "dropoff_lat" numeric(10,7) NOT NULL,
  "dropoff_lng" numeric(10,7) NOT NULL,
  "dropoff_label" text NOT NULL,
  "dropoff_building" varchar(128),
  "dropoff_floor" varchar(32),
  "distance_meters" integer DEFAULT 0 NOT NULL,
  "estimated_duration_sec" integer DEFAULT 0 NOT NULL,
  "actual_duration_sec" integer,
  "passenger_count" smallint DEFAULT 1 NOT NULL,
  "luggage_count" smallint DEFAULT 0 NOT NULL,
  "is_women_only" boolean DEFAULT false NOT NULL,
  "accessibility_needs" jsonb DEFAULT '[]' NOT NULL,
  "coupon_code" varchar(32),
  "scheduled_at" timestamp with time zone,
  "accepted_at" timestamp with time zone,
  "arrived_at" timestamp with time zone,
  "started_at" timestamp with time zone,
  "completed_at" timestamp with time zone,
  "cancelled_at" timestamp with time zone,
  "cancel_reason" text,
  "estimated_fare" numeric(14,2) NOT NULL,
  "final_fare" numeric(14,2),
  "surge_multiplier" numeric(4,2) DEFAULT '1.00' NOT NULL,
  "tip" numeric(14,2) DEFAULT '0' NOT NULL,
  "payment_method" "ride_payment_method" DEFAULT 'upi' NOT NULL,
  "promo_discount" numeric(14,2) DEFAULT '0' NOT NULL,
  "campus_coin_discount" numeric(14,2) DEFAULT '0' NOT NULL,
  "waiting_sec" integer DEFAULT 0 NOT NULL,
  "polyline" text,
  "rating_by_rider" smallint,
  "rating_by_driver" smallint,
  "notes" text,
  "tags" jsonb DEFAULT '[]' NOT NULL,
  "metadata" jsonb DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_tracking_points" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "ride_id" uuid NOT NULL,
  "driver_id" uuid,
  "lat" numeric(10,7) NOT NULL,
  "lng" numeric(10,7) NOT NULL,
  "bearing" numeric(5,2),
  "speed_kph" numeric(6,2),
  "accuracy_m" numeric(6,2),
  "phase" "trip_phase" DEFAULT 'transit' NOT NULL,
  "battery_pct" smallint,
  "recorded_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_pools" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "campus_id" uuid NOT NULL,
  "driver_id" uuid,
  "vehicle_id" uuid,
  "status" "pool_status" DEFAULT 'open' NOT NULL,
  "origin_lat" numeric(10,7) NOT NULL,
  "origin_lng" numeric(10,7) NOT NULL,
  "origin_label" text NOT NULL,
  "destination_lat" numeric(10,7) NOT NULL,
  "destination_lng" numeric(10,7) NOT NULL,
  "destination_label" text NOT NULL,
  "capacity" smallint DEFAULT 4 NOT NULL,
  "seats_taken" smallint DEFAULT 0 NOT NULL,
  "discount_pct" numeric(5,2) DEFAULT '30.00' NOT NULL,
  "detected_at" timestamp with time zone DEFAULT now() NOT NULL,
  "dispatched_at" timestamp with time zone,
  "completed_at" timestamp with time zone,
  "cancelled_at" timestamp with time zone,
  "metadata" jsonb DEFAULT '{}' NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_pool_members" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "pool_id" uuid NOT NULL,
  "ride_id" uuid NOT NULL,
  "rider_id" uuid NOT NULL,
  "join_order" smallint DEFAULT 1 NOT NULL,
  "fare_share" numeric(14,2) NOT NULL,
  "picked_up_at" timestamp with time zone,
  "dropped_off_at" timestamp with time zone
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_fare_configs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "campus_id" uuid NOT NULL,
  "vehicle_type" "vehicle_type" NOT NULL,
  "base_fare" numeric(14,2) NOT NULL,
  "per_km_rate" numeric(14,2) NOT NULL,
  "per_min_rate" numeric(14,2) NOT NULL,
  "min_fare" numeric(14,2) NOT NULL,
  "max_fare" numeric(14,2) NOT NULL,
  "pool_discount" numeric(5,2) DEFAULT '0.30' NOT NULL,
  "night_surcharge" numeric(5,2) DEFAULT '1.25' NOT NULL,
  "waiting_fee_per_min" numeric(14,2) DEFAULT '2.00' NOT NULL,
  "platform_fee" numeric(14,2) DEFAULT '5.00' NOT NULL,
  "gst_pct" numeric(5,2) DEFAULT '5.00' NOT NULL,
  "surge_ceiling" numeric(4,2) DEFAULT '2.50' NOT NULL,
  "effective_from" timestamp with time zone DEFAULT now() NOT NULL,
  "effective_to" timestamp with time zone,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_promotions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "campus_id" uuid,
  "code" varchar(32) NOT NULL,
  "title" varchar(128) NOT NULL,
  "description" text,
  "banner_url" text,
  "discount_type" varchar(16) NOT NULL,
  "discount_value" numeric(14,2) NOT NULL,
  "max_discount" numeric(14,2),
  "min_ride_value" numeric(14,2) DEFAULT '0' NOT NULL,
  "usage_limit" integer,
  "usage_per_user" integer DEFAULT 1 NOT NULL,
  "usage_count" integer DEFAULT 0 NOT NULL,
  "ride_types" jsonb DEFAULT '[]' NOT NULL,
  "applicable_hours" jsonb DEFAULT '{"startHour":0,"endHour":24}' NOT NULL,
  "valid_from" timestamp with time zone DEFAULT now() NOT NULL,
  "valid_until" timestamp with time zone NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_payments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "ride_id" uuid NOT NULL,
  "rider_id" uuid NOT NULL,
  "driver_id" uuid,
  "amount" numeric(14,2) NOT NULL,
  "tax" numeric(14,2) DEFAULT '0' NOT NULL,
  "tip" numeric(14,2) DEFAULT '0' NOT NULL,
  "platform_fee" numeric(14,2) DEFAULT '0' NOT NULL,
  "total" numeric(14,2) NOT NULL,
  "method" "ride_payment_method" NOT NULL,
  "status" "ride_payment_status" DEFAULT 'pending' NOT NULL,
  "gateway_order_id" varchar(128),
  "gateway_payment_id" varchar(128),
  "gateway_signature" text,
  "cod_collected_at" timestamp with time zone,
  "cod_collected_by" uuid,
  "refund_amount" numeric(14,2) DEFAULT '0' NOT NULL,
  "refund_reason" text,
  "refunded_at" timestamp with time zone,
  "invoice_url" text,
  "metadata" jsonb DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_cod_verifications" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "ride_id" uuid NOT NULL,
  "rider_id" uuid NOT NULL,
  "driver_id" uuid,
  "otp_hash" varchar(128) NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "attempts" smallint DEFAULT 0 NOT NULL,
  "max_attempts" smallint DEFAULT 5 NOT NULL,
  "status" "cod_verification_status" DEFAULT 'pending' NOT NULL,
  "verified_at" timestamp with time zone,
  "failure_reason" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_sos_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "ride_id" uuid,
  "triggered_by" uuid NOT NULL,
  "driver_id" uuid,
  "campus_id" uuid NOT NULL,
  "lat" numeric(10,7),
  "lng" numeric(10,7),
  "audio_clip_url" text,
  "video_clip_url" text,
  "note" text,
  "severity" "incident_severity" DEFAULT 'high' NOT NULL,
  "status" "sos_status" DEFAULT 'triggered' NOT NULL,
  "acknowledged_by" uuid,
  "acknowledged_at" timestamp with time zone,
  "resolved_at" timestamp with time zone,
  "authorities_notified" boolean DEFAULT false NOT NULL,
  "authority_reference_id" varchar(128),
  "timeline" jsonb DEFAULT '[]' NOT NULL,
  "metadata" jsonb DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_incidents" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "ride_id" uuid,
  "reported_by" uuid NOT NULL,
  "reported_against" uuid,
  "driver_id" uuid,
  "campus_id" uuid NOT NULL,
  "category" varchar(64) NOT NULL,
  "severity" "incident_severity" DEFAULT 'medium' NOT NULL,
  "description" text NOT NULL,
  "evidence" jsonb DEFAULT '[]' NOT NULL,
  "status" "incident_status" DEFAULT 'reported' NOT NULL,
  "assigned_to" uuid,
  "resolution" text,
  "refunded_amount" numeric(14,2),
  "penalty_issued" boolean DEFAULT false NOT NULL,
  "penalty_amount" numeric(14,2),
  "timeline" jsonb DEFAULT '[]' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_luggage_configs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "ride_id" uuid NOT NULL,
  "rider_id" uuid NOT NULL,
  "pieces" smallint DEFAULT 1 NOT NULL,
  "total_weight_kg" numeric(6,2),
  "size_breakdown" jsonb DEFAULT '[]' NOT NULL,
  "fragile" boolean DEFAULT false NOT NULL,
  "requires_boots" boolean DEFAULT true NOT NULL,
  "assistance" boolean DEFAULT false NOT NULL,
  "notes" text,
  "declared_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_skins" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(128) NOT NULL,
  "rarity" "skin_rarity" DEFAULT 'common' NOT NULL,
  "thumbnail_url" text NOT NULL,
  "hero_url" text,
  "description" text,
  "palette" jsonb NOT NULL,
  "shader_code" text,
  "unlock_criteria" jsonb NOT NULL,
  "is_animated" boolean DEFAULT false NOT NULL,
  "is_limited" boolean DEFAULT false NOT NULL,
  "valid_from" timestamp with time zone DEFAULT now() NOT NULL,
  "valid_until" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_skin_selections" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "skin_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "applied_to_vehicle_id" uuid,
  "selected_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_vehicle_scans" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "vehicle_id" uuid NOT NULL,
  "driver_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "scan_type" varchar(32) NOT NULL,
  "exterior_score" numeric(5,2),
  "interior_score" numeric(5,2),
  "tire_score" numeric(5,2),
  "light_score" numeric(5,2),
  "cleanliness_score" numeric(5,2),
  "model_url" text,
  "thumbnail_url" text,
  "anomalies" jsonb DEFAULT '[]' NOT NULL,
  "raw_report" jsonb DEFAULT '{}' NOT NULL,
  "scan_started_at" timestamp with time zone DEFAULT now() NOT NULL,
  "scan_completed_at" timestamp with time zone
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_maintenance_logs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "vehicle_id" uuid NOT NULL,
  "driver_id" uuid,
  "type" "maintenance_type" NOT NULL,
  "summary" varchar(256) NOT NULL,
  "description" text,
  "parts" jsonb DEFAULT '[]' NOT NULL,
  "labour_cost" numeric(14,2) DEFAULT '0' NOT NULL,
  "parts_cost" numeric(14,2) DEFAULT '0' NOT NULL,
  "total_cost" numeric(14,2) DEFAULT '0' NOT NULL,
  "odometer_km" integer,
  "vendor" varchar(128),
  "invoice_url" text,
  "performed_by" varchar(128),
  "performed_at" timestamp with time zone DEFAULT now() NOT NULL,
  "next_due_at" timestamp with time zone,
  "metadata" jsonb DEFAULT '{}' NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_fleet_deployments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "campus_id" uuid NOT NULL,
  "name" varchar(128) NOT NULL,
  "description" text,
  "zone_ids" jsonb DEFAULT '[]' NOT NULL,
  "driver_ids" jsonb DEFAULT '[]' NOT NULL,
  "vehicle_ids" jsonb DEFAULT '[]' NOT NULL,
  "status" "deployment_status" DEFAULT 'planned' NOT NULL,
  "scheduled_from" timestamp with time zone NOT NULL,
  "scheduled_to" timestamp with time zone NOT NULL,
  "surge_factor" numeric(4,2) DEFAULT '1.00' NOT NULL,
  "notes" text,
  "created_by" uuid,
  "approved_by" uuid,
  "approved_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_heatmap_predictions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "campus_id" uuid NOT NULL,
  "bucket" timestamp with time zone NOT NULL,
  "lat" numeric(10,7) NOT NULL,
  "lng" numeric(10,7) NOT NULL,
  "demand_score" numeric(6,2) NOT NULL,
  "supply_score" numeric(6,2) NOT NULL,
  "recommended_drivers" integer DEFAULT 0 NOT NULL,
  "confidence" numeric(5,2) DEFAULT '0.50' NOT NULL,
  "model_version" varchar(32) DEFAULT 'v1' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_places" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "campus_id" uuid,
  "kind" varchar(32) NOT NULL,
  "label" varchar(128) NOT NULL,
  "address" text,
  "lat" numeric(10,7) NOT NULL,
  "lng" numeric(10,7) NOT NULL,
  "icon" varchar(64),
  "popularity" integer DEFAULT 0 NOT NULL,
  "metadata" jsonb DEFAULT '{}' NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_user_places" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "label" varchar(128) NOT NULL,
  "custom_label" varchar(128),
  "address" text,
  "lat" numeric(10,7) NOT NULL,
  "lng" numeric(10,7) NOT NULL,
  "icon" varchar(64),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "last_used_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_ratings" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "ride_id" uuid NOT NULL,
  "rater_id" uuid NOT NULL,
  "ratee_id" uuid NOT NULL,
  "rating" smallint NOT NULL,
  "tags" jsonb DEFAULT '[]' NOT NULL,
  "comment" text,
  "is_public" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_curators" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "display_name" varchar(128) NOT NULL,
  "avatar_url" text,
  "tier" "curator_tier" DEFAULT 'bronze' NOT NULL,
  "curator_score" numeric(6,2) DEFAULT '0' NOT NULL,
  "rides_curated" integer DEFAULT 0 NOT NULL,
  "issues_resolved" integer DEFAULT 0 NOT NULL,
  "tribes_led" integer DEFAULT 0 NOT NULL,
  "rituals_completed" integer DEFAULT 0 NOT NULL,
  "biweekly_points" integer DEFAULT 0 NOT NULL,
  "lifetime_points" integer DEFAULT 0 NOT NULL,
  "training_completed" jsonb DEFAULT '[]' NOT NULL,
  "joined_at" timestamp with time zone DEFAULT now() NOT NULL,
  "last_active_at" timestamp with time zone DEFAULT now() NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_curator_shifts" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "curator_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "scheduled_start" timestamp with time zone NOT NULL,
  "scheduled_end" timestamp with time zone NOT NULL,
  "checked_in_at" timestamp with time zone,
  "checked_out_at" timestamp with time zone,
  "breaks" jsonb DEFAULT '[]' NOT NULL,
  "status" "curator_shift_status" DEFAULT 'scheduled' NOT NULL,
  "rides_monitored" integer DEFAULT 0 NOT NULL,
  "issues_handled" integer DEFAULT 0 NOT NULL,
  "points_earned" integer DEFAULT 0 NOT NULL,
  "notes" text
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_curator_leaderboard" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "campus_id" uuid NOT NULL,
  "period" varchar(16) NOT NULL,
  "period_start" timestamp with time zone NOT NULL,
  "period_end" timestamp with time zone NOT NULL,
  "curator_id" uuid NOT NULL,
  "rank" integer NOT NULL,
  "score" integer NOT NULL,
  "rides_curated" integer DEFAULT 0 NOT NULL,
  "issues_resolved" integer DEFAULT 0 NOT NULL,
  "bonus_points" integer DEFAULT 0 NOT NULL,
  "reward" jsonb DEFAULT '{"type":"coin","value":0,"label":""}' NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_rewards" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "campus_id" uuid NOT NULL,
  "tier" "curator_tier" DEFAULT 'bronze' NOT NULL,
  "points" integer DEFAULT 0 NOT NULL,
  "lifetime_points" integer DEFAULT 0 NOT NULL,
  "streak_days" integer DEFAULT 0 NOT NULL,
  "badges" jsonb DEFAULT '[]' NOT NULL,
  "milestones" jsonb DEFAULT '[]' NOT NULL,
  "metadata" jsonb DEFAULT '{}' NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "ride_audit_logs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "actor_id" uuid,
  "actor_role" varchar(32),
  "action" varchar(128) NOT NULL,
  "entity" varchar(64) NOT NULL,
  "entity_id" uuid,
  "ride_id" uuid,
  "campus_id" uuid,
  "before" jsonb,
  "after" jsonb,
  "ip_address" varchar(45),
  "user_agent" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- FOREIGN KEYS ──────────────────────────────────────────────────────────

DO $$ BEGIN
  ALTER TABLE "ride_drivers" ADD CONSTRAINT "ride_drivers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_drivers" ADD CONSTRAINT "ride_drivers_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_vehicles" ADD CONSTRAINT "ride_vehicles_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_vehicles" ADD CONSTRAINT "ride_vehicles_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_driver_shifts" ADD CONSTRAINT "ride_driver_shifts_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_driver_shifts" ADD CONSTRAINT "ride_driver_shifts_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_requests" ADD CONSTRAINT "ride_requests_rider_id_users_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_requests" ADD CONSTRAINT "ride_requests_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_requests" ADD CONSTRAINT "ride_requests_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_requests" ADD CONSTRAINT "ride_requests_vehicle_id_ride_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."ride_vehicles"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_tracking_points" ADD CONSTRAINT "ride_tracking_points_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_tracking_points" ADD CONSTRAINT "ride_tracking_points_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_pools" ADD CONSTRAINT "ride_pools_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_pools" ADD CONSTRAINT "ride_pools_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_pools" ADD CONSTRAINT "ride_pools_vehicle_id_ride_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."ride_vehicles"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_pool_members" ADD CONSTRAINT "ride_pool_members_pool_id_ride_pools_id_fk" FOREIGN KEY ("pool_id") REFERENCES "public"."ride_pools"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_pool_members" ADD CONSTRAINT "ride_pool_members_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_pool_members" ADD CONSTRAINT "ride_pool_members_rider_id_users_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_fare_configs" ADD CONSTRAINT "ride_fare_configs_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_promotions" ADD CONSTRAINT "ride_promotions_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_payments" ADD CONSTRAINT "ride_payments_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_payments" ADD CONSTRAINT "ride_payments_rider_id_users_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_payments" ADD CONSTRAINT "ride_payments_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_cod_verifications" ADD CONSTRAINT "ride_cod_verifications_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_cod_verifications" ADD CONSTRAINT "ride_cod_verifications_rider_id_users_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_cod_verifications" ADD CONSTRAINT "ride_cod_verifications_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_sos_events" ADD CONSTRAINT "ride_sos_events_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_sos_events" ADD CONSTRAINT "ride_sos_events_triggered_by_users_id_fk" FOREIGN KEY ("triggered_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_sos_events" ADD CONSTRAINT "ride_sos_events_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_sos_events" ADD CONSTRAINT "ride_sos_events_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_sos_events" ADD CONSTRAINT "ride_sos_events_acknowledged_by_users_id_fk" FOREIGN KEY ("acknowledged_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_incidents" ADD CONSTRAINT "ride_incidents_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_incidents" ADD CONSTRAINT "ride_incidents_reported_by_users_id_fk" FOREIGN KEY ("reported_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_incidents" ADD CONSTRAINT "ride_incidents_reported_against_users_id_fk" FOREIGN KEY ("reported_against") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_incidents" ADD CONSTRAINT "ride_incidents_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_incidents" ADD CONSTRAINT "ride_incidents_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_incidents" ADD CONSTRAINT "ride_incidents_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_luggage_configs" ADD CONSTRAINT "ride_luggage_configs_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_luggage_configs" ADD CONSTRAINT "ride_luggage_configs_rider_id_users_id_fk" FOREIGN KEY ("rider_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_skin_selections" ADD CONSTRAINT "ride_skin_selections_skin_id_ride_skins_id_fk" FOREIGN KEY ("skin_id") REFERENCES "public"."ride_skins"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_skin_selections" ADD CONSTRAINT "ride_skin_selections_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_skin_selections" ADD CONSTRAINT "ride_skin_selections_applied_to_vehicle_id_ride_vehicles_id_fk" FOREIGN KEY ("applied_to_vehicle_id") REFERENCES "public"."ride_vehicles"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_vehicle_scans" ADD CONSTRAINT "ride_vehicle_scans_vehicle_id_ride_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."ride_vehicles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_vehicle_scans" ADD CONSTRAINT "ride_vehicle_scans_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_vehicle_scans" ADD CONSTRAINT "ride_vehicle_scans_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_maintenance_logs" ADD CONSTRAINT "ride_maintenance_logs_vehicle_id_ride_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."ride_vehicles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_maintenance_logs" ADD CONSTRAINT "ride_maintenance_logs_driver_id_ride_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "public"."ride_drivers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_fleet_deployments" ADD CONSTRAINT "ride_fleet_deployments_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_fleet_deployments" ADD CONSTRAINT "ride_fleet_deployments_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_fleet_deployments" ADD CONSTRAINT "ride_fleet_deployments_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_heatmap_predictions" ADD CONSTRAINT "ride_heatmap_predictions_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_places" ADD CONSTRAINT "ride_places_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_user_places" ADD CONSTRAINT "ride_user_places_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_ratings" ADD CONSTRAINT "ride_ratings_ride_id_ride_requests_id_fk" FOREIGN KEY ("ride_id") REFERENCES "public"."ride_requests"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_ratings" ADD CONSTRAINT "ride_ratings_rater_id_users_id_fk" FOREIGN KEY ("rater_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_ratings" ADD CONSTRAINT "ride_ratings_ratee_id_users_id_id_fk" FOREIGN KEY ("ratee_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_curators" ADD CONSTRAINT "ride_curators_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_curators" ADD CONSTRAINT "ride_curators_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_curator_shifts" ADD CONSTRAINT "ride_curator_shifts_curator_id_ride_curators_id_fk" FOREIGN KEY ("curator_id") REFERENCES "public"."ride_curators"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_curator_shifts" ADD CONSTRAINT "ride_curator_shifts_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_curator_leaderboard" ADD CONSTRAINT "ride_curator_leaderboard_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_curator_leaderboard" ADD CONSTRAINT "ride_curator_leaderboard_curator_id_ride_curators_id_fk" FOREIGN KEY ("curator_id") REFERENCES "public"."ride_curators"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_rewards" ADD CONSTRAINT "ride_rewards_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  ALTER TABLE "ride_rewards" ADD CONSTRAINT "ride_rewards_campus_id_campuses_id_fk" FOREIGN KEY ("campus_id") REFERENCES "public"."campuses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- INDEXES ───────────────────────────────────────────────────────────────

CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_drivers_user" ON "ride_drivers" ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_drivers_campus" ON "ride_drivers" ("campus_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_drivers_status" ON "ride_drivers" ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_drivers_campus_status" ON "ride_drivers" ("campus_id","status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_drivers_geo" ON "ride_drivers" ("current_lat","current_lng");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_vehicles_driver" ON "ride_vehicles" ("driver_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_vehicles_campus_status" ON "ride_vehicles" ("campus_id","status");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_vehicles_plate" ON "ride_vehicles" ("license_plate");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_driver_shifts_driver" ON "ride_driver_shifts" ("driver_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_driver_shifts_started" ON "ride_driver_shifts" ("started_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_requests_rider" ON "ride_requests" ("rider_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_requests_driver" ON "ride_requests" ("driver_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_requests_campus" ON "ride_requests" ("campus_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_requests_status" ON "ride_requests" ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_requests_campus_status" ON "ride_requests" ("campus_id","status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_requests_created" ON "ride_requests" ("created_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_requests_pickup_geo" ON "ride_requests" ("pickup_lat","pickup_lng");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_tracking_ride" ON "ride_tracking_points" ("ride_id","recorded_at");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_tracking_driver" ON "ride_tracking_points" ("driver_id","recorded_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_pools_campus_status" ON "ride_pools" ("campus_id","status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_pools_detected" ON "ride_pools" ("detected_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_pool_members_pool" ON "ride_pool_members" ("pool_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_pool_members_ride" ON "ride_pool_members" ("ride_id");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_fare_configs_unique" ON "ride_fare_configs" ("campus_id","vehicle_type","effective_from");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_promotions_code" ON "ride_promotions" ("code");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_promotions_campus" ON "ride_promotions" ("campus_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_payments_ride" ON "ride_payments" ("ride_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_payments_rider" ON "ride_payments" ("rider_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_payments_status" ON "ride_payments" ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_payments_gateway" ON "ride_payments" ("gateway_order_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_cod_ride" ON "ride_cod_verifications" ("ride_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_cod_status" ON "ride_cod_verifications" ("status");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_sos_ride" ON "ride_sos_events" ("ride_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_sos_status" ON "ride_sos_events" ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_sos_campus" ON "ride_sos_events" ("campus_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_sos_created" ON "ride_sos_events" ("created_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_incidents_ride" ON "ride_incidents" ("ride_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_incidents_status" ON "ride_incidents" ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_incidents_campus" ON "ride_incidents" ("campus_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_incidents_category" ON "ride_incidents" ("category");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_luggage_ride" ON "ride_luggage_configs" ("ride_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_skins_rarity" ON "ride_skins" ("rarity");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_skin_sel_user" ON "ride_skin_selections" ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_skin_sel_skin" ON "ride_skin_selections" ("skin_id");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_vehicle_scans_vehicle" ON "ride_vehicle_scans" ("vehicle_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_vehicle_scans_driver" ON "ride_vehicle_scans" ("driver_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_vehicle_scans_type" ON "ride_vehicle_scans" ("scan_type");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_maint_vehicle" ON "ride_maintenance_logs" ("vehicle_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_maint_type" ON "ride_maintenance_logs" ("type");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_maint_performed" ON "ride_maintenance_logs" ("performed_at");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_deploy_campus_status" ON "ride_fleet_deployments" ("campus_id","status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_deploy_scheduled" ON "ride_fleet_deployments" ("scheduled_from");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_heatmap_campus_bucket" ON "ride_heatmap_predictions" ("campus_id","bucket");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_heatmap_geo" ON "ride_heatmap_predictions" ("lat","lng");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_places_campus_kind" ON "ride_places" ("campus_id","kind");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_places_geo" ON "ride_places" ("lat","lng");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_user_places_user" ON "ride_user_places" ("user_id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_user_places_label" ON "ride_user_places" ("user_id","label");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_ratings_ride" ON "ride_ratings" ("ride_id","rater_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_ratings_ratee" ON "ride_ratings" ("ratee_id","created_at");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_curators_user" ON "ride_curators" ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_curators_campus" ON "ride_curators" ("campus_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_curators_score" ON "ride_curators" ("curator_score");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_curator_shifts_curator" ON "ride_curator_shifts" ("curator_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_curator_shifts_sched" ON "ride_curator_shifts" ("scheduled_start");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_curator_shifts_status" ON "ride_curator_shifts" ("status");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_curator_lb_campus_period" ON "ride_curator_leaderboard" ("campus_id","period","period_start");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_curator_lb_rank" ON "ride_curator_leaderboard" ("campus_id","period","period_start","curator_id");
--> statement-breakpoint

CREATE UNIQUE INDEX IF NOT EXISTS "idx_ride_rewards_user" ON "ride_rewards" ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_rewards_campus" ON "ride_rewards" ("campus_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_rewards_points" ON "ride_rewards" ("points");
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "idx_ride_audit_actor" ON "ride_audit_logs" ("actor_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_audit_entity" ON "ride_audit_logs" ("entity","entity_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ride_audit_created" ON "ride_audit_logs" ("created_at");
--> statement-breakpoint

-- POSTGIS GEOSPATIAL INDICES (if extension is available) ───────────────

DO $$ BEGIN
  PERFORM 1 FROM pg_extension WHERE extname = 'postgis';
EXCEPTION WHEN OTHERS THEN NULL; END $$;
--> statement-breakpoint

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'postgis') THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_ride_drivers_postgis ON ride_drivers USING gist (ll_to_earth(current_lat::float8, current_lng::float8))';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_ride_requests_pickup_postgis ON ride_requests USING gist (ll_to_earth(pickup_lat::float8, pickup_lng::float8))';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_ride_requests_dropoff_postgis ON ride_requests USING gist (ll_to_earth(dropoff_lat::float8, dropoff_lng::float8))';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_ride_places_postgis ON ride_places USING gist (ll_to_earth(lat::float8, lng::float8))';
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_ride_heatmap_postgis ON ride_heatmap_predictions USING gist (ll_to_earth(lat::float8, lng::float8))';
  END IF;
END $$;
--> statement-breakpoint

-- Default Row Level Security scaffolding (admin bypasses, ids are uuid) ──

ALTER TABLE "ride_drivers" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_vehicles" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_requests" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_tracking_points" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_payments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_ratings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_sos_events" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_incidents" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_user_places" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_rewards" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_curators" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_curator_shifts" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_curator_leaderboard" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ride_audit_logs" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint

-- RLS policies: drivers see their own row, riders see their own rides,
-- curators see their campus data. Admin role bypasses RLS entirely.

DO $$ BEGIN
  CREATE POLICY "ride_drivers_self_select" ON "ride_drivers"
    FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE POLICY "ride_requests_rider_select" ON "ride_requests"
    FOR SELECT USING (auth.uid() = rider_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE POLICY "ride_requests_driver_select" ON "ride_requests"
    FOR SELECT USING (
      EXISTS (
        SELECT 1 FROM ride_drivers d
        WHERE d.id = ride_requests.driver_id AND d.user_id = auth.uid()
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE POLICY "ride_user_places_owner" ON "ride_user_places"
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE POLICY "ride_rewards_owner" ON "ride_rewards"
    FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE POLICY "ride_curators_campus_read" ON "ride_curators"
    FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE POLICY "ride_curator_lb_public" ON "ride_curator_leaderboard"
    FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

DO $$ BEGIN
  CREATE POLICY "ride_ratings_public" ON "ride_ratings"
    FOR SELECT USING (is_public = true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint

-- SEED ANCHOR: a system row for audit log to reference when no actor is
-- known (e.g. background job cancelling a stale ride).

INSERT INTO "ride_audit_logs" ("actor_id", "actor_role", "action", "entity", "entity_id", "before", "after", "ip_address", "user_agent", "created_at")
SELECT NULL, 'system', 'migration:0002_ride_and_go', 'schema', NULL, NULL, '{"applied":true}', '127.0.0.1', 'drizzle-kit/0002_ride_and_go',
       now()
WHERE NOT EXISTS (SELECT 1 FROM "ride_audit_logs" WHERE "action" = 'migration:0002_ride_and_go');
--> statement-breakpoint